trigger:
  branches:
    include:
    - none
variables:
- name: functionAppName
  value: 'zpy38func'
- name: vmImageName
  value: 'ubuntu-latest'
- name: workingDirectory
  value: '$(System.DefaultWorkingDirectory)/'
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Bash@3
      displayName: 'Build extensions'
      inputs:
        targetType: inline
        script: |
          if [ -f extensions.csproj ]
          then
              dotnet build extensions.csproj --runtime ubuntu.16.04-x64 --output ./bin
          fi
        workingDirectory: $(workingDirectory)
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.8'
      inputs:
        versionSpec: 3.8
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: echo "=========zzzzzzzz==== build is succcessful for this project======="
- stage: DEV_Deploy_Stage
  displayName: DEV Deploy stage
  dependsOn:
  - Build
  condition: succeeded()
  jobs:
  - deployment: DEV_Deploy_Job
    displayName: DEV_Deploy_Job
    environment:
      name: 'dev'
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            displayName: 'app deploy to dev Environment'
            inputs:
              targetType: 'inline'
              script: echo "=========zzzzzzzz==== dev deployment is succcessful for this project======="
- stage: TEST_Deploy_Stage
  displayName: TEST Deploy stage
  dependsOn:
  - DEV_Deploy_Stage
  condition: succeeded()
  jobs:
  - deployment: TEST_Deploy_Job
    displayName: TEST_Deploy_Job
    environment:
      name: 'test'
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            displayName: 'app deploy to test Environment'
            inputs:
              targetType: 'inline'
              script: echo "=========zzzzzzzz==== Test deployment is succcessful for this project======="
- stage: PROD_Deploy_Stage
  displayName: PROD Deploy stage
  dependsOn:
  - TEST_Deploy_Stage
  condition: succeeded()
  jobs:
  - deployment: PROD_Deploy_Job
    displayName: PROD_Deploy_Job
    environment:
      name: 'prod'
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            displayName: 'app deploy to prod Environment with approval'
            inputs:
              targetType: 'inline'
              script: echo "=========zzzzzzzz==== prod deployment is succcessful for this project======="

